import numpy as np
import tulipy as ti
import yfinance as yf
import pandas as pd
import sys
import backtester

np.set_printoptions(threshold=sys.maxsize)
tickerLst = pd.read_csv("../StockTickers/TickerNames.csv", header=None)
while True:
    try:
        [sampleTicker, sample] = backtester.chooseSample(tickerLst)
        break
    except:
        pass
print(sampleTicker)
print(sample)
openn = sample["Open"].to_numpy()
high = sample["High"].to_numpy()
low = sample["Low"].to_numpy()
close = sample["Close"].to_numpy()
volume = sample["Volume"].to_numpy()
print(close)
ad = ti.ad(high, low, close, volume)
print(ad, len(ad))
adosc = ti.adosc(high, low, close, volume, 2, 5)
print(adosc, len(adosc))
adx = ti.adx(high, low, close, 5)
print(adx, len(adx))
adxr = ti.adxr(high, low, close, 5)
print(adxr, len(adxr))
ao = ti.ao(high, low)
print(ao, len(ao))
apo = ti.apo(close, 2, 5)
print(apo, len(apo))
aroon = ti.aroon(high, low, 5)
print(aroon[0], len(aroon[0]))
print(aroon[1], len(aroon[1]))
aroonosc = ti.aroonosc(high, low, 5)
print(aroonosc, len(aroonosc))
atr = ti.atr(high, low, close, 5)
print(atr, len(atr))
bop = ti.bop(openn, high, low, close)
print(bop, len(bop))
cci = ti.cci(high, low, close, 5)
print(cci, len(cci))
cmo = ti.cmo(close, 5)
print(cmo, len(cmo))
cvi = ti.cvi(high, low, 5)
print(cvi, len(cvi))
di = ti.di(high, low, close, 5)
print(di[0], len(di[0]))
print(di[1], len(di[1]))
dm = ti.dm(high, low, 5)
print(dm[0], len(dm[0]))
print(dm[1], len(dm[1]))
dpo = ti.dpo(close, 5)
print(dpo, len(dpo))
dx = ti.dx(high, low, close, 5)
print(dx, len(dx))
emv = ti.emv(high, low, volume)
print(emv, len(emv))
fisher = ti.fisher(high, low, 5)
print(fisher[0], len(fisher[0]))
print(fisher[1], len(fisher[1]))
fosc = ti.fosc(close, 5)
print(fosc, len(fosc))
kvo = ti.kvo(high, low, close, volume, 2, 5)
print(kvo, len(kvo))
linregintercept = ti.linregintercept(close, 5)
print(linregintercept, len(linregintercept))
linregslope = ti.linregslope(close, 5)
print(linregslope, len(linregslope))
macd = ti.macd(close, 2, 5, 9)
print(macd[0], len(macd[0]))
print(macd[1], len(macd[1]))
print(macd[2], len(macd[2]))
marketfi = ti.marketfi(high, low, volume)
print(marketfi, len(marketfi))
mass = ti.mass(high, low, 5)
print(mass, len(mass))
mfi = ti.mfi(high, low, close, volume, 5)
print(mfi, len(mfi))
mom = ti.mom(close, 5)
print(mom, len(mom))
msw = ti.msw(close, 5)
print(msw[0], len(msw[0]))
print(msw[1], len(msw[1]))
natr = ti.natr(high, low, close, 5)
print(natr, len(natr))
nvi = ti.nvi(close, volume)
print(nvi, len(nvi))
obv = ti.obv(close, volume)
print(obv, len(obv))
ppo = ti.ppo(close, 2, 5)
print(ppo, len(ppo))
pvi = ti.pvi(close, volume)
print(pvi, len(pvi))
qstick = ti.qstick(openn, close, 5)
print(qstick, len(qstick))
roc = ti.roc(close, 5)
print(roc, len(roc))
rocr = ti.rocr(close, 5)
print(rocr, len(rocr))
rsi = ti.rsi(close, 5)
print(rsi, len(rsi))
stoch = ti.stoch(high, low, close, 5, 3, 3)
print(stoch[0], len(stoch[0]))
print(stoch[1], len(stoch[1]))
stochrsi = ti.stochrsi(close, 5)
print(stochrsi, len(stochrsi))
tr = ti.tr(high, low, close)
print(tr, len(tr))
trix = ti.trix(close, 5)
print(trix, len(trix))
ultosc = ti.ultosc(high, low, close, 2, 3, 5)
print(ultosc, len(ultosc))
vhf = ti.vhf(close, 5)
print(vhf, len(vhf))
vosc = ti.vosc(close, 2, 5)
print(vosc, len(vosc))
wad = ti.wad(high, low, close)
print(wad, len(wad))
willr = ti.willr(high, low, close)
print(willr, len(willr))
