name: Tradobot Commit Tests

on: [ pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: x64
      - name: Install dependencies
        run: |
          pip3 install .
          pip3 uninstall -y numpy
          pip3 install numpy==1.20.2
      - name: Pylint, Flake8 and Pydocstyle
        run: |
          ./lint2.sh
  # test:
  #   strategy:
  #     matrix:
  #       python-version: [3.7, 3.8]
  #     fail-fast: false
  #   name: Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Setup python
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #         architecture: x64
  #     - name: Install dependencies
  #       run: |
  #         pip3 install .
  #         pip3 install -r requirements.txt
  #         pip3 uninstall -y numpy
  #         pip3 install numpy==1.20.2
  #     - name: Run Tests
  #       run: |
  #         python -m pytest
  #     - name: Upload Test Output
  #       if: always()
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: test_output-${{matrix.os}}-python-${{matrix.python-version}}.csv
  #         path: output.csv
          

